/*=============================================================================
  AUSTRALIAN IMMUNISATION REGISTER (AIR) — SNOWFLAKE DEMO
  Script 5: Manual Refresh — Force all Dynamic Tables to refresh now
  
  Run this after initial data load to see results immediately
  (otherwise they auto-refresh within the TARGET_LAG period)
=============================================================================*/

USE DATABASE AIR_DEMO;
USE WAREHOUSE AIR_DEMO_WH;

-- Silver layer (run in order — downstream tables depend on upstream)
ALTER DYNAMIC TABLE SILVER.PATIENTS REFRESH;
ALTER DYNAMIC TABLE SILVER.PROVIDERS REFRESH;
ALTER DYNAMIC TABLE SILVER.VACCINATIONS REFRESH;
ALTER DYNAMIC TABLE SILVER.VACCINATION_EVENTS REFRESH;

-- Gold layer
ALTER DYNAMIC TABLE GOLD.COVERAGE_BY_STATE_AGE REFRESH;
ALTER DYNAMIC TABLE GOLD.MONTHLY_VACCINATION_TRENDS REFRESH;
ALTER DYNAMIC TABLE GOLD.PROVIDER_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE GOLD.DATA_QUALITY_SUMMARY REFRESH;
ALTER DYNAMIC TABLE GOLD.CHILDHOOD_COVERAGE_MILESTONES REFRESH;

-- Verify row counts
SELECT 'SILVER.PATIENTS' AS dt, COUNT(*) AS rows FROM SILVER.PATIENTS
UNION ALL SELECT 'SILVER.PROVIDERS', COUNT(*) FROM SILVER.PROVIDERS
UNION ALL SELECT 'SILVER.VACCINATIONS', COUNT(*) FROM SILVER.VACCINATIONS
UNION ALL SELECT 'SILVER.VACCINATION_EVENTS', COUNT(*) FROM SILVER.VACCINATION_EVENTS
UNION ALL SELECT 'GOLD.COVERAGE_BY_STATE_AGE', COUNT(*) FROM GOLD.COVERAGE_BY_STATE_AGE
UNION ALL SELECT 'GOLD.MONTHLY_VACCINATION_TRENDS', COUNT(*) FROM GOLD.MONTHLY_VACCINATION_TRENDS
UNION ALL SELECT 'GOLD.PROVIDER_PERFORMANCE', COUNT(*) FROM GOLD.PROVIDER_PERFORMANCE
UNION ALL SELECT 'GOLD.DATA_QUALITY_SUMMARY', COUNT(*) FROM GOLD.DATA_QUALITY_SUMMARY
UNION ALL SELECT 'GOLD.CHILDHOOD_COVERAGE_MILESTONES', COUNT(*) FROM GOLD.CHILDHOOD_COVERAGE_MILESTONES
ORDER BY 1;
